
services:

  db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=changeme
      - POSTGRES_DB=dappertransaction
    ports:
      - '5432:5432'
